spring:
  datasource:
    url: jdbc:mysql://<YOUR_HOST>:3306/notes_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: <YOUR_USERNAME>
    password: <YOUR_PASSWORD>
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
